### ISSUE TITLE
Remove unused variables from ./config.js

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightlite#21]
`./config.js` contains some unused variables, and some duplicate variables (such as `TREE_HEIGHT` & `MERKLE_DEPTH`; or `MERKLE_HASHLENGTH` & `NODE_HASHLENGTH`).

Can these be removed?

**Comment by willKim19** [comment]
Good catch! Will do

**Comment by iAmMichaelConnor** [comment]
Closing - see #24
